# Fichero con la configuración global común para todos los entornos de ejecución
spring:
  profiles:
    # Indica a Spring que use la configuración asociada al perfil activo actualmente
    active: '@activatedProperties@'

  datasource:
    tomcat:
      max-active: 8
      max-idle: 2
      max-wait: 5000
      remove-abandoned: true
      remove-abandoned-timeout: 15
      log-abandoned: true
    driver-class-name: org.postgresql.Driver

  devtools:
    restart:
      trigger-file: reload
    livereload:
      enabled: true

  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

server:
  servlet:
    context-path: '@project.contextPath@'

project:
  jwt:
    signKey: mySecretSignKey
    expirationMinutes: 60

